#define PLAYLIST_Alpha 1
#define PLAYLIST_Beta 2
#define PLAYLIST_Gamma 3
#define PLAYLIST_Delta 4
#define CMD_Stop 64
#define CMD_Pause 65
#define CMD_Loop 66
#define CMD_Repeat 67
#define CMD_Shuffle 68
#define CMD_NextSong 69
#define CMD_PreviousSong 70
#define CMD_Mute 71
#define CMD_Full 72
#define CMD_Half 73
#define CMD_OneQuater 74
#define CMD_ThreeQuater 75
#define CMD_Louder 76
#define CMD_Quieter 77
#define CMD_Resume 78
#define CMD_TrackInfo 79
#define CMD_Preserve 80
#define CMD_Release 81
#define MODE_TrackInfo 250
#define MODE_Playback 251
#define MODE_Volume 252
#define MODE_Playlist 253
#define MODE_Select 254
